kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: skaha-workload-cavern-pvc
  namespace: skaha-workload
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-cephfs-workload
  storageClassName: rook-cephfs
  volumeMode: Filesystem
