kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: skaha-pvc
  namespace: skaha-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
